name: Dependency review
on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: moderate   # 閾値は好みで high/critical などに調整可
