name: OSV scan
on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  osv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: OSV-Scanner
        uses: google/osv-scanner-action@v1
        with:
          scan-args: >-
            --repo .
