name: Python application

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Install uv
        run: |
          powershell -ExecutionPolicy ByPass -c "irm https://astral.sh/uv/install.ps1 | iex"
      - name: Install dependencies
        run: |
          uv init -p 3.10.7
          uv run python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then uv add -r requirements.txt; fi


