name: Python application

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: windows-latest
    defaults: { run: { shell: pwsh } }
    steps:
      - uses: actions/checkout@v5

      # uv を使う（CI上では Python を別途入れなくてOK）
      - uses: astral-sh/setup-uv@v6

      # ロックに従って同期（再現性）。テストを回す場合のみ必要
      - name: Sync deps (locked) and test
        run: |
          uv sync --locked --dev
          uv run -m pytest

      # デプロイ用パッケージを作る
      - name: Package
        run: |
          $zip = "package.zip"
          if (Test-Path $zip) { Remove-Item $zip -Force }
          # 必要なファイルを列挙（例）
          Compress-Archive -Path @(
            "src","app.py",
            "pyproject.toml","uv.lock","README.md"
          ) -DestinationPath $zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: package.zip